# Generated by Django 3.2.4 on 2021-06-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210615_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='department',
        ),
    ]
