# Generated by Django 3.2.4 on 2021-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_subject_allotted_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=1),
        ),
    ]
