# Generated by Django 3.2.4 on 2021-06-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210615_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Answer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('answer_words', models.CharField(max_length=500, null=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.answerpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
