# Generated by Django 3.2.4 on 2021-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210615_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_details',
            name='count',
            field=models.CharField(max_length=5),
        ),
    ]
