# Generated by Django 3.2.4 on 2021-06-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_answer_details_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_details',
            name='count',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='answer_details',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
