# Generated by Django 3.2.4 on 2021-06-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210616_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer_details',
            old_name='count',
            new_name='number_of_pages',
        ),
    ]
