# Generated by Django 3.2.4 on 2021-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210616_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_key_details',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
