# Generated by Django 3.2.4 on 2021-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_answer_key_details_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkeypaper',
            name='answer_sheet',
        ),
        migrations.AddField(
            model_name='answerkeypaper',
            name='answer_key',
            field=models.FileField(null=True, upload_to='Files/answer_keyss'),
        ),
    ]
