# Generated by Django 4.0.5 on 2022-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_allotted_subject_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_id',
        ),
        migrations.AddField(
            model_name='student',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Registrations_No',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
