# Generated by Django 4.0.5 on 2022-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_department_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Registrations_No',
            field=models.IntegerField(null=True),
        ),
    ]
