# Generated by Django 4.0.5 on 2022-06-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_student_registrations_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email_id',
        ),
    ]
