# Generated by Django 4.0.5 on 2022-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_student_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotted_subject',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
