# Generated by Django 4.0.5 on 2022-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_allotted_subject_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer_details',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answer_details',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='answer_details',
            name='student',
        ),
        migrations.RemoveField(
            model_name='answer_key_details',
            name='answer_key',
        ),
        migrations.RemoveField(
            model_name='answer_key_details',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='result',
            name='teacher_evaluated',
        ),
        migrations.RemoveField(
            model_name='score_model',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='score_model',
            name='answer_key',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Answer_details',
        ),
        migrations.DeleteModel(
            name='Answer_key_details',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Score_model',
        ),
    ]
