# Generated by Django 4.0.5 on 2022-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_subject_code_remove_allotted_subject_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='academic',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='subject_code',
            name='subject_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
