# Generated by Django 4.0.5 on 2022-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='mark',
        ),
        migrations.AddField(
            model_name='mark',
            name='Subject1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='Subject2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='Subject3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='assignment1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='assignment2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='assignment3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='attendence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='notes',
            field=models.FileField(null=True, upload_to='adminapp/document'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
