# Generated by Django 4.0.5 on 2022-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_mark_mark_mark_subject1_mark_subject2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('Subject1', models.CharField(max_length=30, null=True)),
                ('Subject2', models.CharField(max_length=30, null=True)),
                ('Subject3', models.CharField(max_length=30, null=True)),
                ('mark1', models.IntegerField(null=True)),
                ('mark2', models.IntegerField(null=True)),
                ('mark3', models.IntegerField(null=True)),
                ('attendence', models.CharField(max_length=30, null=True)),
                ('assignment1', models.CharField(max_length=500, null=True)),
                ('assignment2', models.CharField(max_length=500, null=True)),
                ('assignment3', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
