# Generated by Django 4.0.5 on 2022-06-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_details_delete_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerKeyPaper',
        ),
        migrations.DeleteModel(
            name='AnswerPaper',
        ),
        migrations.DeleteModel(
            name='count_model',
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
